/**
 * Fixtures that hold the backend's characterisation to the console's (PHASE-03).
 *
 * Writes three files to `tests/fixtures/characterise/`:
 *
 *  - `authored_slicks.json`: every authored scenario's slick outline as drawn,
 *    with the point the generator started it from (the paper's suspected-source
 *    tip, or the release point carried forward) and the P004-reported length.
 *    `tests/test_geometry.py` measures the outlines with
 *    `backend/characterize/geometry.py` and holds it to PHASE-03's acceptance
 *    lines: lengths near P004's, an end within 1 km of the source tip.
 *  - `verdict_cases.json`: inputs and the TypeScript verdict for the rubric's
 *    constructed cases and for every run the console has. `check:verdict`
 *    asserts the TypeScript still gives these outputs; `tests/test_verdict.py`
 *    asserts `backend/characterize/verdict.py` gives the same ones.
 *  - `wind_gate.json`: `windGate` over a sweep of speeds, for
 *    `tests/test_windgate.py`.
 *
 * Re-run after changing `sim/slick.ts`, `sim/verdict.ts` or a scenario:
 *   npm run export:characterise-fixtures
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { windGate } from '../src/sim/slick';
import { verdictFrom, verdictInputsFor, type VerdictInputs } from '../src/sim/verdict';
import { buildRun, SCENARIOS } from '../src/sim/scenarios';
import { setTrafficLoader, type RealTrafficFile } from '../src/sim/realAis';
import { ensureRealRun, REAL_RUN_LISTINGS, setRealRunLoader } from '../src/sim/realRun';
import { useDiskTraffic } from './realAisDisk';
import { useDiskLandmask } from './landmaskDisk';
import { CONSTRUCTED_VERDICT_CASES } from './verdictCases';

const out = fileURLToPath(new URL('../../tests/fixtures/characterise/', import.meta.url));
mkdirSync(out, { recursive: true });

// P004 (Zhao et al. 2025) reports these lengths; PHASE-03 names them as acceptance lines.
const P004: Record<string, { case: string; lengthKm: number } | undefined> = {
  'gom-moving': { case: 'Case 2', lengthKm: 19 },
  'gom-platform': { case: 'Case 1', lengthKm: 5.5 },
  'gom-berthed': { case: 'Case 3', lengthKm: 5 },
};

await useDiskTraffic();
useDiskLandmask();

const slicks = [];
const verdicts: { name: string; inputs: VerdictInputs; expected: ReturnType<typeof expected> }[] = [];

function expected(inputs: VerdictInputs) {
  const v = verdictFrom(inputs);
  return {
    verdict: v.verdict,
    support: v.support,
    caution: v.caution,
    terms: Object.fromEntries(v.terms.map((t) => [t.key, t.value])),
  };
}

for (const [name, inputs] of Object.entries(CONSTRUCTED_VERDICT_CASES)) {
  verdicts.push({ name, inputs, expected: expected(inputs) });
}

for (const { id } of SCENARIOS) {
  const run = buildRun(id);
  const c = run.characterisation;
  slicks.push({
    id,
    parts: run.detection.parts,
    // The generator starts the ribbon here: its head is the source tip by construction.
    source: c.head,
    p004: P004[id] ?? null,
    console: {
      lengthKm: c.lengthKm, areaKm2: c.areaKm2, widthMMean: c.widthMMean, elongation: c.elongation,
      orientationDeg: c.orientationDeg, fragmentation: c.fragmentation, head: c.head, tail: c.tail,
    },
  });
  const inputs = verdictInputsFor(run);
  verdicts.push({ name: `scenario ${id}`, inputs, expected: expected(inputs) });
}

const pub = (p: string) => fileURLToPath(new URL(`../public/${p}`, import.meta.url));
if (REAL_RUN_LISTINGS.every(({ id, scene }) => existsSync(pub(`runs/${scene}/drift.json`)) && existsSync(pub(`ais/${id}.json`)))) {
  setRealRunLoader(async (p) => JSON.parse(readFileSync(pub(p), 'utf8')));
  setTrafficLoader(async (s) => JSON.parse(readFileSync(pub(`ais/${s}.json`), 'utf8')) as RealTrafficFile);
  for (const { id } of REAL_RUN_LISTINGS) {
    await ensureRealRun(id);
    const inputs = verdictInputsFor(buildRun(id));
    verdicts.push({ name: `real ${id}`, inputs, expected: expected(inputs) });
  }
} else {
  console.log('real runs not on disk: their verdict cases are left out');
}

const speeds = Array.from({ length: 161 }, (_, i) => i / 10);
const gates = speeds.map((ms) => ({ ms, gate: windGate(ms) }));

const note = 'Generated by frontDemo/scripts/export-characterise-fixtures.ts; do not edit by hand.';
writeFileSync(`${out}authored_slicks.json`, JSON.stringify({ note, slicks }, null, 1));
writeFileSync(`${out}verdict_cases.json`, JSON.stringify({ note, cases: verdicts }, null, 1));
writeFileSync(`${out}wind_gate.json`, JSON.stringify({ note, gates }, null, 1));
console.log(`wrote ${slicks.length} authored slicks, ${verdicts.length} verdict cases, ${gates.length} wind-gate speeds to ${out}`);
