/**
 * VII -- LIMITATIONS.
 *
 * Where this file stops being reliable, set in the same weight of type as the
 * findings in front of it.
 *
 * A system that names vessels as suspected polluters and does not publish where
 * it stops being certain is not a usable system, it is a confident one. So the
 * limits are a numbered part of the document rather than small print under it,
 * and the source classification that every exhibit in Parts I to V carries is
 * finally set out in full here: what is published, what is model output, and
 * what is generated by the simulation running in this page.
 */

import {
  COMPARISON,
  LIMITS,
  PROVENANCE,
  PUBLISHED,
  SIMULATED,
  TERM_NOTE,
  TERM_ORIGIN,
} from "../../../content";
import { TERM_LABEL, TERM_ORDER, ageStatement, dateline } from "../../../lib/format";
import type { Run } from "../../../sim/types";
import type { ShellProps } from "../../registry";

import {
  SOURCE_LABEL,
  Facing,
  FacingColumn,
  Footnotes,
  Head,
  Leaf,
  MarginNote,
  Micro,
  PartTitle,
  Prose,
  Register,
  Rule,
  Stamp,
  caseRef,
} from "../components";

export default function Limitations({ state }: ShellProps) {
  const { run } = state;

  return (
    <>
      <PartTitle
        numeral="VII"
        title="Limitations"
        standfirst="The conditions under which the reconstruction in Part III and the analysis in Part V stop being reliable, and the classification of every source this file draws on."
      />

      {/* ---------------------------------------------------------------- *
          The limits
       * ---------------------------------------------------------------- */}
      <Leaf
        margin={
          <MarginNote label="Standing">
            These are not caveats attached to a conclusion. They are the reasons
            the conclusion in Part VI takes the form it does, and on one of the
            five cases in this series they are the reason there is no conclusion
            at all.
          </MarginNote>
        }
      >
        <Head level={3}>Stated limits</Head>
        <div className="mt-6">
          {LIMITS.map((l, i) => (
            <article
              key={l.key}
              className="grid grid-cols-1 gap-x-8 border-t py-6 lg:grid-cols-[3rem_minmax(0,1fr)]"
              style={{ borderColor: "var(--line)" }}
            >
              <div>
                <span
                  className="num text-[13px]"
                  style={{ color: "var(--accent)" }}
                >
                  {String(i + 1).padStart(2, "0")}
                </span>
              </div>
              <div>
                <h4
                  className="text-[clamp(1.05rem,1.5vw,1.3rem)] leading-[1.2]"
                  style={{ fontFamily: "var(--font-display)", color: "var(--ink)" }}
                >
                  {l.title}
                </h4>
                <p
                  className="mt-1.5 font-mono text-[9.5px] tracking-[0.2em] uppercase"
                  style={{ color: "var(--ink-faint)" }}
                >
                  {l.short}
                </p>
                <Prose className="mt-3">{l.body}</Prose>
              </div>
            </article>
          ))}
        </div>
      </Leaf>

      {/* ---------------------------------------------------------------- *
          The same limits, on this case
       * ---------------------------------------------------------------- */}
      {run && <OnThisCase run={run} />}

      {/* ---------------------------------------------------------------- *
          Source classification
       * ---------------------------------------------------------------- */}
      <Leaf
        margin={
          <div>
            <MarginNote label="Classification">
              Every exhibit in this file is stamped with one of four
              classifications. The distinction is the whole reason the stamp is a
              required part of an exhibit rather than an optional caption line.
            </MarginNote>
            <div className="mt-4">
              <Stamp tone="accent" angle={-3.6}>
                {PROVENANCE.flag}
              </Stamp>
            </div>
          </div>
        }
      >
        <Rule weight="firm" className="mb-6" />
        <Head level={3}>Classification of sources</Head>

        <Prose className="mt-4" tone="ink">
          {PROVENANCE.full}
        </Prose>

        <div className="mt-7">
          <Register
            head={["Stamp", "Meaning"]}
            width={["12rem", undefined]}
            dense
            rows={(
              [
                ["published", "Taken from a peer-reviewed publication. Acquisition times, slick lengths and suspected-source coordinates for the Gulf of Mexico cases, plus the instrument parameters and the wind band."],
                ["model", "Produced by the pipeline on this page: contours, credible regions, characterisation, scores."],
                ["simulated", "Generated for this demonstration and not a measurement of anything. Radar imagery, currents, wind, and every AIS track."],
                ["authored", "Ground truth written by us rather than derived from a detector, so the evaluation cannot be circular."],
              ] as [keyof typeof SOURCE_LABEL, string][]
            ).map(([k, meaning]) => ({
              key: k,
              cells: [
                <span
                  className="font-mono text-[10px] tracking-[0.18em] uppercase"
                  style={{ color: "var(--accent)" }}
                >
                  {SOURCE_LABEL[k]}
                </span>,
                <span className="text-[11.5px] leading-[1.5]">{meaning}</span>,
              ],
            }))}
          />
        </div>

        <div className="mt-8">
          <Facing>
            <FacingColumn label="Taken from published work">
              <ul>
                {PUBLISHED.map((p) => (
                  <li key={p} className="mb-3 flex gap-3">
                    <span
                      className="num mt-[3px] shrink-0 text-[9px]"
                      style={{ color: "var(--ink-faint)" }}
                      aria-hidden
                    >
                      ▪
                    </span>
                    <span
                      className="text-[12.5px] leading-[1.55]"
                      style={{ fontFamily: "var(--font-body)", color: "var(--ink-dim)" }}
                    >
                      {p}
                    </span>
                  </li>
                ))}
              </ul>
            </FacingColumn>

            <FacingColumn label="Generated by the simulation" tone="accent" ruled>
              <ul>
                {SIMULATED.map((p) => (
                  <li key={p} className="mb-3 flex gap-3">
                    <span
                      className="num mt-[3px] shrink-0 text-[9px]"
                      style={{ color: "var(--accent)" }}
                      aria-hidden
                    >
                      ▪
                    </span>
                    <span
                      className="text-[12.5px] leading-[1.55]"
                      style={{ fontFamily: "var(--font-body)", color: "var(--ink-dim)" }}
                    >
                      {p}
                    </span>
                  </li>
                ))}
              </ul>
            </FacingColumn>
          </Facing>
        </div>

        {run && (
          <p
            className="text-faint mt-7 max-w-[70ch] text-[11.5px] leading-[1.5]"
            style={{ fontFamily: "var(--font-body)" }}
          >
            For this case specifically: {run.meta.provenance}
          </p>
        )}
      </Leaf>

      {/* ---------------------------------------------------------------- *
          Against the prior art
       * ---------------------------------------------------------------- */}
      <Leaf
        margin={
          <MarginNote label="Where the terms come from">
            Four of the six terms are the operational reference system's, kept at
            their relative ordering so the comparison stays legible. Two are this
            project's, and one of those is the reason the file has a Part III at
            all.
          </MarginNote>
        }
      >
        <Rule weight="firm" className="mb-6" />
        <Head level={3}>Against the prior art</Head>

        <div className="mt-5">
          <Register
            head={["System", "Detection", "Drift", "AIS", "Explanation"]}
            rows={COMPARISON.map((c) => ({
              key: c.system,
              mark: !!c.ours,
              cells: [
                <span
                  className="font-mono text-[10px] tracking-[0.14em] uppercase"
                  style={{ color: c.ours ? "var(--accent)" : "var(--ink)" }}
                >
                  {c.system}
                </span>,
                <span className="text-[11.5px]">{c.detect}</span>,
                <span className="text-[11.5px]">{c.drift}</span>,
                <span className="text-[11.5px]">{c.ais}</span>,
                <span className="text-[11.5px]">{c.explain}</span>,
              ],
            }))}
          />
        </div>

        <div className="mt-8">
          <Micro tone="ink" className="mb-3">
            The six terms and their provenance
          </Micro>
          <Register
            head={["Term", "Origin", "Note"]}
            width={["9rem", "8rem", undefined]}
            dense
            rows={TERM_ORDER.map((k) => ({
              key: k,
              mark: TERM_ORIGIN[k] === "This project",
              cells: [
                <span className="font-mono text-[10.5px] tracking-[0.12em] uppercase">
                  {TERM_LABEL[k]}
                </span>,
                <span className="font-mono text-[10px] tracking-[0.1em] uppercase">
                  {TERM_ORIGIN[k]}
                </span>,
                <span className="text-[11.5px] leading-[1.5]">{TERM_NOTE[k]}</span>,
              ],
            }))}
          />
        </div>
      </Leaf>

      <Leaf pad="tight" margin={<Micro>Notes</Micro>}>
        <Footnotes
          items={[
            <>
              Vessel names appearing in the published case studies this work is
              validated against are used solely to check the method against its
              stated ground truth. No vessel is named anywhere in this interface,
              and identities are masked in every register and every exhibit.
            </>,
            <>
              Ingested AIS is not redistributed beyond this demonstration. Every
              track shown in this file is generated rather than replayed.
            </>,
          ]}
        />
      </Leaf>
    </>
  );
}

/* ------------------------------------------------------------------ *
 * The limits, applied
 * ------------------------------------------------------------------ */

/**
 * Which of the stated limits actually bore on the file in hand.
 *
 * Without this sheet Part VII was the same document on all five cases: six
 * fixed limits, a fixed classification table and a fixed comparison, with one
 * provenance sentence at the very bottom as the only thing that moved. A reader
 * who opened a different case from the rail while reading it saw nothing change
 * anywhere in the viewport, which is most of why switching case appeared to do
 * nothing at all.
 *
 * It is also the more honest sheet. A list of limits that reads identically
 * whether or not any of them bit is a disclaimer; a list that says which ones
 * decided this case is a statement about the method. Every reading below comes
 * off the run on this page, and nothing here is computed that the run does not
 * already carry.
 */
function OnThisCase({ run }: { run: Run }) {
  const c = run.characterisation;
  const d = run.drift;
  const ref = caseRef(run);
  const age = ageStatement(d);
  const diffuse = d.insufficientEvidence;

  // The same reduction Part III prints its convergence figure from, so the two
  // sheets cannot disagree about the tightest the origin field ever got.
  const tightest = d.convergence.reduce(
    (m, x) => Math.min(m, x.area90Km2),
    Infinity,
  );
  // The same threshold Part II calls a weak gate.
  const gateWeak = c.windGateMultiplier < 0.75;
  const dark = run.suspects.filter((s) => s.kind === "dark_vessel").length;
  // Matches Part VI: a diffuse field and an empty candidate list are the same
  // finding, and neither issues an attribution.
  const withheld = !!diffuse || run.suspects.length === 0;

  const facts: Record<string, { bit: boolean; reading: string; note: string }> = {
    diffusion: {
      bit: !!diffuse,
      reading: Number.isFinite(tightest) ? `${tightest.toFixed(0)} km²` : "—",
      note: diffuse
        ? `The field never focused far enough to choose between candidates. ${diffuse.reason}`
        : "The origin field closed far enough for the candidates in Part V to be separated by it.",
    },
    lookalike: {
      bit: gateWeak,
      reading: `×${c.windGateMultiplier.toFixed(2)} at ${c.windSpeedMs.toFixed(1)} m/s`,
      note: gateWeak
        ? "Wind low enough that a biogenic film would flatten the surface the same way. The gate carries that doubt forward as a multiplier on every score in Part V rather than dropping the detection and saying nothing."
        : "Wind inside the band where oil damps the surface and the common look-alikes do not, so the gate takes almost nothing off this case.",
    },
    dark: {
      bit: dark > 0,
      reading: dark === 0 ? "None" : `${dark} unlit contact${dark === 1 ? "" : "s"}`,
      note:
        dark === 0
          ? "Every candidate ranked on this case carries an AIS association."
          : "Ranked on the same six terms as every other candidate, and never named. The identity stays masked in every register and every exhibit in this file.",
    },
    thickness: {
      bit: false,
      reading: `${c.dampingRatioDb.toFixed(1)} dB, confidence ${c.dampingConfidence}`,
      note: "A relative contrast index between the slick and the water around it. This case reports no thickness and no spilled volume, because the system has no field for either.",
    },
    forcing: {
      bit: age.degenerate,
      reading: age.value,
      note: `Age by ${age.method}: ${age.phrase}. The width of that statement is where the coarseness of the forcing ends up, and it is not narrowed to look better.`,
    },
    determination: {
      bit: withheld,
      reading: withheld ? "Withheld" : "Candidate only",
      note: withheld
        ? "Part VI issues no attribution on this case. Every candidate is still scored and the working is still printed, because the reasoning has to stay open to challenge whether or not it reaches a candidate."
        : "Part VI issues a ranked candidate and nothing further. Nothing on this case is called responsible or confirmed, and the alternative hypotheses stay beside the top-ranked one.",
    },
  };

  const bitCount = LIMITS.filter((l) => facts[l.key]?.bit).length;

  return (
    <Leaf
      margin={
        <div>
          <MarginNote label="Applied">
            The six limits above are printed identically on every file in this
            series. Which of them actually bore on the case in hand is not, and
            that is what this sheet records.
          </MarginNote>
          <div className="mt-4">
            <Stamp tone={withheld ? "accent" : "faint"} angle={-3.1} size="small">
              {withheld ? "Attribution withheld" : "Candidate only"}
            </Stamp>
          </div>
        </div>
      }
    >
      <Rule weight="firm" className="mb-6" />
      <Micro tone="accent">
        Case {ref.number} · {dateline(run.meta.acquiredAt)}
      </Micro>
      <Head level={3} className="mt-3">
        How these limits bore on this case
      </Head>

      <Prose className="mt-4">
        This file is a {run.meta.place} acquisition, filed as {ref.file}. Of the
        six limits stated above,{" "}
        {bitCount === 0
          ? "none bore"
          : bitCount === 1
            ? "one bore"
            : `${bitCount} bore`}{" "}
        materially on it. The readings in the register below are this case's
        own.
      </Prose>

      {/* The diffuse finding is the loudest thing on any sheet that carries it,
          here as in Parts III and VI. It is stated before the register rather
          than as a marked row inside it, because a row is something a reader
          can skim past. */}
      {diffuse && (
        <div
          className="mt-7 border-y py-7"
          style={{ borderColor: "var(--accent)", borderWidth: "2px 0" }}
          role="status"
        >
          <div className="mb-5">
            <Stamp tone="accent" size="large" angle={-4.4}>
              No attribution issued
            </Stamp>
          </div>
          <Micro tone="accent">Which limit decided this file</Micro>
          <Head level={2} className="mt-3" style={{ color: "var(--accent)" }}>
            Limit 01. The origin field never focused.
          </Head>
          <Prose className="mt-4" tone="ink">
            {diffuse.reason}
          </Prose>
          <p className="num text-faint mt-3 text-[12px]">
            Tightest 90% origin region {diffuse.area90Km2.toFixed(0)} km²
          </p>
        </div>
      )}

      <div className="mt-7">
        <Register
          caption="Numbered as the stated limits above"
          head={["", "Limit", "On this case", "What that means here"]}
          width={["2.5rem", "13rem", "11rem", undefined]}
          rows={LIMITS.map((l, i) => {
            const f = facts[l.key];
            return {
              key: l.key,
              cells: [
                <span
                  className="num text-[11px]"
                  style={{ color: f.bit ? "var(--accent)" : "var(--ink-faint)" }}
                >
                  {String(i + 1).padStart(2, "0")}
                </span>,
                <span
                  className="font-mono text-[9.5px] tracking-[0.14em] uppercase"
                  style={{ color: "var(--ink-dim)" }}
                >
                  {l.short}
                </span>,
                <span
                  className="num text-[11.5px]"
                  style={{ color: f.bit ? "var(--accent)" : "var(--ink)" }}
                >
                  {f.reading}
                </span>,
                <span className="text-[11.5px] leading-[1.5]">{f.note}</span>,
              ],
            };
          })}
        />
      </div>

      <p
        className="text-faint mt-6 max-w-[70ch] text-[11.5px] leading-[1.5]"
        style={{ fontFamily: "var(--font-body)" }}
      >
        A reading set in oxide is a limit that bore on this case. One left in ink
        is stated because it is always true of the method, not because it changed
        anything here.
      </p>
    </Leaf>
  );
}
