/**
 * The opening, and the first question: what is on the water.
 *
 * The page opens on a statement of the problem rather than on a product pitch,
 * and the first thing under it is the radar frame with the instance mask
 * converged onto it -- the one image that explains what the whole system is
 * looking at. Dossier's `SarPlate` draws it: the annotations are laid out in the
 * tile's own pixel space with leader lines back to what they name, so the
 * callouts cannot drift off the feature they describe.
 *
 * The figure sits *beside* the prose rather than under it. It is a portrait
 * plate, and a portrait plate run full width leaves half the row empty on both
 * sides while pushing everything that follows a screen further down.
 */

import { PRODUCT } from "../../content";
import { clock, dateline } from "../../lib/format";
import type { SpillState } from "../../lib/spill";
import {
  Body,
  Head,
  Kicker,
  Note,
  Page,
  SectionMark,
  Standfirst,
  Tag,
  Wide,
} from "../components";
import { SarPlate } from "../plates";
import { Row } from "../instruments";
import { SpillSelect } from "../SpillSelect";
import { ConsoleKey } from "../Nav";
import { Loading } from "../Loading";

export function Opening() {
  return (
    <section className="pt-12 pb-16 sm:pt-16">
      <Page>
        {/*
          The hero does not use `Spread`.

          It used to, and it was the worst thing on the page: the body grid gave
          it an empty 5rem gutter, trapped an 86px headline in a 62ch measure so
          fifty-four characters broke into four ragged lines, and left the
          provenance note alone at the top of a column with seven hundred pixels
          of nothing under it.

          An opening spread is a different object from a reading spread. The
          headline gets the full width and breaks in two; everything that
          supports it sits in one band underneath, so the block ends where the
          content ends.
        */}
        {/* `data-ship-start` moors the gutter tanker level with the kicker.
            It is marked here rather than measured as an offset so that moving
            the hero around cannot leave the ship sailing from nowhere. */}
        <div data-ship-start>
          <Kicker>Oil at sea, from orbit</Kicker>

          <Head level={1} className="mt-5">
            Something is leaking. Find out what, and who was there.
          </Head>

          <div className="mt-11 grid grid-cols-1 gap-x-12 gap-y-9 md:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,15rem)]">
            <Standfirst>{PRODUCT.summary}</Standfirst>

            <Body>
              Radar satellites see the ocean through cloud and darkness, and oil
              flattens the small waves that radar bounces off — so a slick reads
              as a dark patch. That much is old. What is hard is everything
              after: telling oil from the many other things that flatten the
              sea, working out where it started rather than where it has drifted
              to, and deciding which of the ships in the area could have put it
              there.
            </Body>

            <Note label="Provenance">
              Every figure on this page is generated by a simulation running in
              your browser. No model has been trained yet, and nothing here is a
              measurement of one. Each figure says so.
            </Note>
          </div>

          <div
            className="mt-10 flex flex-wrap items-center gap-5 border-t pt-8"
            style={{ borderColor: 'var(--line)' }}
          >
            <ConsoleKey large />
            <span className="text-faint font-mono text-[10px] tracking-[0.2em] uppercase">
              or read on
            </span>
          </div>
        </div>
      </Page>
    </section>
  );
}

/** `Port of South Louisiana · 15 MAY 2023 00:02Z`, on one line. */
function sceneLine(place: string, at: number): string {
  return `${place.replace(/^the /i, "")} · ${dateline(at)} ${clock(at)}Z`;
}

export function Spills({ spill }: { spill: SpillState }) {
  const { run } = spill;
  const c = run?.characterisation;

  return (
    <section id="spills" ref={spill.ref} className="scroll-mt-[70px] py-14">
      <Page>
        <SectionMark index={1} kicker="Detection" title="What is on the water" />

        <Wide className="mt-9">
          {/*
            The figure column is sized to the plate, not to whatever is left.

            `1fr` here measured 873px around a 414px portrait plate -- the same
            dead-space fault this pass exists to remove, reintroduced one level
            down. `auto` sizes the column to the plate, and the grid centres the
            pair, so the caption rule, the image and the control below it all
            share one width.
          */}
          <div className="grid grid-cols-1 gap-x-14 gap-y-10 lg:grid-cols-[minmax(0,1fr)_auto] lg:justify-between">
            {/* --- the reading column -------------------------------- */}
            <div>
              <Body>
                A radar image of the sea is mostly noise — speckle, the grainy
                interference pattern that makes radar look nothing like a
                photograph. Oil suppresses the surface roughness that produces
                the return, so a slick appears as a region of lower mean
                backscatter inside that noise. It is not a dark object pasted
                onto the water; it is a change in the statistics of the water
                itself, which is why the boundary is a judgement rather than an
                edge.
              </Body>
              <Body className="mt-4">
                The detector outlines it as an instance mask in two classes — an
                operational discharge, or a slick whose origin is unknown. The
                plate beside this shows one such acquisition with the mask
                converged onto it. The contour matters more than the label:
                everything downstream, the backward drift especially, is seeded
                inside this shape.
              </Body>

              {run && c && (
                <div
                  className="mt-8 border-t pt-5"
                  style={{ borderColor: "var(--line)" }}
                >
                  <div className="space-y-1.5">
                    <Row label="Area" value={`${c.areaKm2.toFixed(2)} km²`} />
                    <Row label="Length" value={`${c.lengthKm.toFixed(1)} km`} />
                    <Row label="Mean width" value={`${c.widthMMean.toFixed(0)} m`} />
                    <Row label="Elongation" value={c.elongation.toFixed(1)} />
                    <Row label="Damping" value={`${c.dampingRatioDb.toFixed(1)} dB`} />
                    {/*
                      C9: the wind gate is a continuous multiplier the interface
                      has to show, never a silent filter. It used to be a gauge
                      further down the page; the gauge is gone and this row is
                      what keeps the requirement met.
                    */}
                    <Row
                      label="Wind"
                      value={`${c.windSpeedMs.toFixed(1)} m/s · gate ×${c.windGateMultiplier.toFixed(2)}`}
                    />
                  </div>

                  <p className="text-faint mt-4 text-[12.5px] leading-[1.55]">
                    Damping is a relative contrast index, not a thickness. There
                    is no field anywhere in this system for microns, or for
                    spilled volume — remote sensing cannot currently supply
                    either. The wind gate scales the detection's confidence
                    rather than filtering it away, so a detection in flat air
                    visibly loses weight instead of quietly disappearing.
                  </p>
                </div>
              )}
            </div>

            {/* --- the plate ------------------------------------------ */}
            <div className="lg:w-fit">
              {run ? (
                <figure className="lg:w-fit">
                  {/* Figure number hard left, the scene on one line hard
                      right, with a rule carrying the eye between them. The
                      caption is place and time only -- the sentence that used
                      to live here is prose, and prose belongs in the column
                      to the left. */}
                  <figcaption
                    className="flex items-baseline gap-4 border-b pb-2"
                    style={{ borderColor: "var(--line)" }}
                  >
                    <Tag tone="accent">Figure 1</Tag>
                    <span
                      className="h-px min-w-4 flex-1"
                      style={{ background: "var(--line)" }}
                      aria-hidden
                    />
                    <span className="text-dim truncate font-mono text-[10px] tracking-[0.14em] whitespace-nowrap uppercase">
                      {sceneLine(run.meta.place, run.meta.acquiredAt)}
                    </span>
                  </figcaption>

                  <div className="mt-4">
                    <SarPlate run={run} height={620} />
                  </div>

                  <div className="mt-5 flex justify-center">
                    <SpillSelect spill={spill} center />
                  </div>
                </figure>
              ) : (
                <Loading label="Building the scene" height={620} />
              )}
            </div>
          </div>
        </Wide>
      </Page>
    </section>
  );
}
