"""Retrain the release configuration on final-v12 (FUTURE_WORK.md section 0, job 1, step 4).

    .venv/Scripts/python.exe -m scripts.train_v12 --smoke   # 1 epoch on final-v11, must equal the release's epoch 1
    .venv/Scripts/python.exe -m scripts.train_v12           # 100 epochs on final-v12; re-run to resume a chunk

Same cell, overrides, batch, workers, seed and FP32-safe trainer as
`scripts/retrain_final_l1.py`; only the dataset differs. `runs/` did not survive
the move to this machine, so the shared initial head (`runs/final/initial_head.pt`)
is regenerated by `scripts/train_final.py`'s own deterministic recipe. The smoke
run is what proves that recipe gave back the same head: the release checkpoint
carries its own per-epoch results, and a fresh epoch 1 on final-v11 must reproduce
them.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Any

import torch

from ml.ablation.run_ablation import ChunkLimitReachedError, load_pretrained_backbone, run_cell
from ml.models.yolo_seg_lsk import register_lsk, write_config
from ml.train.checkpoint import FP32ReleaseTrainer
from scripts.retrain_final_l1 import CELL, EPOCHS
from scripts.train_final import HEAD, OVERRIDES, ROOT, digest

V11 = ROOT / "data/processed/dataset/final-v11"
V12 = ROOT / "data/processed/dataset/final-v12"
PROJECT = ROOT / "runs/final_v12_l1"
SMOKE = ROOT / "runs/smoke_v11_l1"
RELEASE = ROOT / "weights/L1-ciou-research-v11.pt"  # the release v12 was compared with
COMPARED = (
    "train/box_loss",
    "train/seg_loss",
    "train/cls_loss",
    "train/dfl_loss",
    "metrics/mAP50(M)",
    "metrics/mAP50-95(M)",
    "metrics/mAP50(B)",
    "metrics/mAP50-95(B)",
    "val/box_loss",
    "val/seg_loss",
    "val/cls_loss",
    "val/dfl_loss",
)


def ensure_head() -> str:
    """`train_final.prepare`'s head recipe, verbatim, if the file is missing."""

    from ultralytics import YOLO
    from ultralytics.utils.torch_utils import init_seeds

    register_lsk()
    torch.set_num_threads(6)
    if not HEAD.exists():
        HEAD.parent.mkdir(parents=True, exist_ok=True)
        init_seeds(0, deterministic=True)
        config = write_config("none", HEAD.parent / "configs/yolo11n-seg-none.yaml")
        model = YOLO(str(config), task="segment")
        load_pretrained_backbone(model, str(ROOT / "yolo11n-seg.pt"), "none")
        network: Any = model.model
        torch.save(network.model[-1].state_dict(), HEAD)
        print(f"regenerated {HEAD}", flush=True)
    return str(digest(HEAD))


def train(data: Path, project: Path, max_minutes: float) -> None:
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA unavailable: refusing to train on the CPU")
    print(f"GPU: {torch.cuda.get_device_name(0)}", flush=True)
    run_cell(
        CELL,
        data=data / "data.yaml",
        epochs=EPOCHS,
        project=project,
        batch=4,
        workers=2,
        seed=0,
        max_minutes=max_minutes,
        full_resources=True,
        overrides={**OVERRIDES, "trainer": FP32ReleaseTrainer},
        config_dir=project / "configs",
        initial_head=HEAD,
    )


def smoke() -> int:
    """Epoch 1 on final-v11 against the release's own epoch-1 row."""

    head = ensure_head()
    try:
        train(V11, SMOKE, max_minutes=0.1)  # the boundary is checked after each epoch
    except ChunkLimitReachedError as event:
        print(f"stopped as intended: {event}", flush=True)
    with (SMOKE / CELL.name / "results.csv").open(newline="") as handle:
        fresh = {k.strip(): float(v) for k, v in next(csv.DictReader(handle)).items()}
    release = torch.load(RELEASE, map_location="cpu", weights_only=False)["train_results"]
    rows = {key: (float(release[key][0]), fresh[key]) for key in COMPARED}
    identical = all(round(a, 5) == round(b, 5) for a, b in rows.values())
    for key, (a, b) in rows.items():
        print(
            f"  {key:<22} release {a:.5f}   fresh {b:.5f}   {'=' if round(a, 5) == round(b, 5) else 'DIFFERS'}"
        )
    record = {"head_sha256": head, "identical_to_5dp": identical, "epoch1": rows}
    (SMOKE / "smoke.json").write_text(json.dumps(record, indent=2), encoding="utf-8")
    print(
        "SMOKE",
        "PASSED: regenerated head and pipeline reproduce the release" if identical else "FAILED",
    )
    return 0 if identical else 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--max-minutes", type=float, default=240.0)
    arguments = parser.parse_args()
    if arguments.smoke:
        return smoke()
    if not (V12 / "data.yaml").exists():
        print(f"no {V12}; run scripts.part_two build first", file=sys.stderr)
        return 2
    smoke_record = SMOKE / "smoke.json"
    if not smoke_record.exists() or not json.loads(smoke_record.read_text())["identical_to_5dp"]:
        print("the smoke check has not passed; run --smoke first", file=sys.stderr)
        return 2
    if ensure_head() != json.loads(smoke_record.read_text())["head_sha256"]:
        raise RuntimeError("initial head changed since the smoke check")
    try:
        train(V12, PROJECT, arguments.max_minutes)
    except ChunkLimitReachedError as event:
        print(f"PAUSED: {event} -- run again to resume", flush=True)
        return 3
    print("final-v12 L1 training complete", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
