/**
 * Where the water stops.
 *
 * The drift integrator was a random walk on an unbounded plane, so backward
 * reconstruction put origins on top of the Mississippi delta and ran the Kutch
 * scene across the Saurashtra peninsula. Oil does not drift through Louisiana,
 * and a hindcast that says it came from Venice is not a weak result, it is a
 * wrong one -- the whole claim of the system is that the origin field is
 * somewhere a vessel could have been.
 *
 * The mask is generated by `scripts/build_landmask.py` from the same Esri Ocean
 * basemap the map draws, so the shoreline the integrator respects is the
 * shoreline the operator sees. A mask taken from some other coastline product
 * would disagree with the rendered coast at exactly the zoom levels where the
 * disagreement shows.
 *
 * Cells are about 550 m and cover only the coastal boxes that scenes actually
 * reach. Anything outside every box is open water, which is correct for this
 * corpus -- the boxes were drawn around the coasts, and everything beyond them
 * is the open Gulf or the Arabian Sea.
 */

import { LAND_BOXES, type LandBox } from "./landmask.generated";

interface Decoded extends LandBox {
  bytes: Uint8Array;
}

/**
 * Decoded lazily and once.
 *
 * Roughly half a million cells across the three boxes. Unpacking to one byte
 * per cell would cost half a megabyte of heap for a lookup that is already O(1)
 * against the packed form, so the bits stay packed and the accessor shifts.
 */
let decoded: Decoded[] | null = null;

function boxes(): Decoded[] {
  if (decoded) return decoded;
  decoded = LAND_BOXES.map((box) => {
    const binary = atob(box.bits);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return { ...box, bytes };
  });
  return decoded;
}

/** True when this coordinate is dry ground. */
export function isLand(lon: number, lat: number): boolean {
  for (const box of boxes()) {
    if (lon < box.west || lon >= box.east || lat < box.south || lat >= box.north) continue;
    const col = Math.floor((lon - box.west) / box.cell);
    const row = Math.floor((lat - box.south) / box.cell);
    if (col < 0 || col >= box.nx || row < 0 || row >= box.ny) continue;
    const index = row * box.nx + col;
    return (box.bytes[index >> 3] & (1 << (index & 7))) !== 0;
  }
  return false;
}

/**
 * The fraction of a path that lies on land, sampled at `steps` points.
 *
 * This is the programmatic form of the by-hand corridor check recorded in
 * `scenarios.ts`. It exists so a shipping lane can be verified against the same
 * mask the drift uses, rather than against a separate reading of the basemap.
 */
export function landFraction(
  from: [number, number],
  to: [number, number],
  steps = 25,
): number {
  let ashore = 0;
  for (let i = 0; i < steps; i++) {
    const t = steps === 1 ? 0 : i / (steps - 1);
    if (isLand(from[0] + (to[0] - from[0]) * t, from[1] + (to[1] - from[1]) * t)) ashore++;
  }
  return ashore / steps;
}
